############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1


[[main]]
name = "Family Trove App"
url = "/family-trove"
weight = 2

[[main]]
name = "About"
url = "/about"
weight = 3

# [[main]]
# name = "Blog"
# url = "/blog"

# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Family Trove App"
url = "/family-trove"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
